version: 2

models:
  - name: fact_transactions
    description: |
      Transaction fact table containing detailed transaction-level data.

      Grain: One row per transaction

      This fact table:
      - Links to customer and product dimensions
      - Stores all transaction measures
      - Includes temporal attributes for time-based analysis
      - Denormalizes some dimension attributes for query performance

      In production, this would typically be materialized incrementally.

    meta:
      owner: data-engineering
      data_steward: business-analytics
      contains_pii: true
      pii_columns: ['customer_fk']
      data_classification: confidential
      retention_days: 2555  # 7 years
      business_domain: sales_analytics

    columns:
      - name: transaction_key
        description: Primary key - unique identifier for each transaction
        tests:
          - unique
          - not_null
      
      - name: customer_fk
        description: Foreign key to dim_customers
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
      
      - name: product_fk
        description: Foreign key to dim_products
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_key
      
      - name: transaction_date
        description: Date when the transaction occurred
        tests:
          - not_null
      
      - name: transaction_month
        description: First day of month when transaction occurred
        tests:
          - not_null
      
      - name: transaction_year
        description: Year when transaction occurred
        tests:
          - not_null
      
      - name: transaction_quarter
        description: Quarter (1-4) when transaction occurred
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
      
      - name: units_sold
        description: Number of units sold in this transaction (additive)
        tests:
          - not_null
      
      - name: gross_amount
        description: Transaction amount before tax (additive)
        tests:
          - not_null
      
      - name: tax_amount
        description: Tax applied to the transaction (additive)
        tests:
          - not_null
      
      - name: net_amount
        description: Total transaction amount including tax (additive)
        tests:
          - not_null
      
      - name: revenue_excluding_tax
        description: Revenue amount excluding tax (additive)
        tests:
          - not_null
      
      - name: unit_price
        description: Price per unit (non-additive)
        tests:
          - not_null
      
      - name: customer_tier
        description: Denormalized customer tier at time of transaction
        tests:
          - not_null
      
      - name: customer_value_segment
        description: Denormalized customer value segment
        tests:
          - not_null
      
      - name: product_name
        description: Denormalized product name
        tests:
          - not_null
      
      - name: product_price_tier
        description: Denormalized product price tier
        tests:
          - not_null
      
      - name: product_revenue_segment
        description: Denormalized product revenue segment
        tests:
          - not_null
      
      - name: created_at
        description: Timestamp when the fact record was created
        tests:
          - not_null